server.port=8083
spring.application.name=ms-notification

# Fila de origem
app.queue.notification=${NOTIFICATION_QUEUE_NAME:notification-queue.fifo}

# ============================================================================
# Endpoint do LocalStack
# ============================================================================
spring.cloud.aws.endpoint=${AWS_ENDPOINT_URL:http://localhost:4566}
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}

# SQS Listener
spring.cloud.aws.sqs.listener.max-messages-per-poll=10
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.sqs.listener.max-concurrent-messages=10

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# Padrao de log
logging.pattern.level=%5p [%X{correlationId:-}]
