spring:
  ai:
    model:
      chat: anthropic
      embedding: ollama        # embedding sempre no Ollama, mesmo com chat na nuvem
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        model: claude-haiku-4-5
        max-tokens: 1024
        temperature: 0.1
    ollama:
      base-url: http://localhost:11435   # container Ollama
      embedding:
        model: bge-m3
    vectorstore:
      pgvector:
        dimensions: 1024       # casa com o bge-m3d